### ISSUE TITLE
Inheritance for SpecIF classes

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#10]
An inheritance relation is helpful to maintain consistent class definitions. The idea is that an instance (e.g. resource) of a certain class (resourceClass in this case) may use all propertyClasses of the chain of ancestor classes. The same applies to subjectClasses and objectClasses in case of statements.

**Comment by odungern** [comment]
@oalt and anybody else:
- Which keyword is preferrable to indicate inheritance: 'extends', 'inheritsFrom' or 'specializes'?
- or any other proposal?  

I myself would prefer 'extends' as it is used in TypeScript.

**Comment by oalt** [comment]
Possible alternatives:
* Java, TypeScript: extends
* C++, C#: ':' (not applicable for SpecIF)
* EIFFEL: inherit
* RDF (https://www.w3.org/TR/rdf-schema/#ch_subclassof): rdfs:subClassOf

**Comment by odungern** [comment]
Today I have specifically checked whether Dublin Core has an inheritance concept ... it has not.

**Comment by oalt** [comment]
I vote for 'extends' :-)

**Comment by oalt** [comment]
@odungern: Would you like to use a relation (statement) to express the inheritance or a new JSON property?
I think a JSON property is enough, because we need a possibility to express, that e.g. a ResourceClass extends another one. 
So it could look like this:
 {
      "id": "RC-Requirement",
      "title": "IREB:Requirement",
      "description": "A 'Requirement' is a singular documented physical and functional need that a particular design, product or process must be able to perform.",
      "icon": "&#8623;",
      "instantiation": [ "user" ],
      "propertyClasses": ["PC-VisibleId", "PC-Name", "PC-Text", "PC-Status", "PC-Priority", "PC-Perspective", "PC-Discipline"],
      "revision": 1,
      "changedAt": "2016-05-26T08:59:00+02:00"
},
{
      "id": "RC-AutomotiveRequirement",
      "title": "SpecIF:AutomotiveRequirement",
     **"extends" : "RC-Requirement",**
      "description": "A 'Requirement' is a singular documented physical and functional need that a particular design, product or process must be able to perform.",
      "icon": "A",
      "instantiation": [ "user" ],
      "propertyClasses": ["PC-SupplierStatus", "PC-SupplierComment", "PC-OemStatus", "PC-OemComment"],
      "revision": 1,
      "changedAt": "2016-05-26T08:59:00+02:00"
}

**Comment by odungern** [comment]
Thanks, @oalt , 
Exactly, I think a property is sufficient ... and your proposal is exactly what I had in mind. There are no relations between classes, anyways.

**Comment by odungern** [comment]
Has been implemented for SpecIF-Level-1, see https://specif.de/v0.10.7/schema.
The schema for SpecIF-Level-3 will come shortly with https://specif.de/v0.11.7/schema.
The consistency checkers will take a couple of weeks.

**Comment by odungern** [comment]
Schema of SpecIF-Level-3 has been enhanced, see https://specif.de/v0.11.7/schema.
The consistency checker will be updated accordingly in the coming weeks.

**Comment by odungern** [comment]
The consistency checker for v0.10.8 and v0.11.8 checks whether the id given als value for 'extends' is a resource resp statement class.
