### ISSUE TITLE
Enumerated dataTypes may have multi-language values

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#13]
In SpecIF-level-3 (master branch), the titles of the values of an enumerated dataType shall be specified in different languages. Then, a viewer can display the enumerated values in the appropriate language. 
The  specification may be viewed completely language-dependent:
- The viewer (tool) may translate the SpecIF vocabulary terms to the desired language
- The author may provide the values of an enumerated dataType in different languages, the viewer selects the appropriate text value according to the desired language.
- The property text values, equally.

**Comment by odungern** [comment]
Schema of SpecIF-Level-3 has been enhanced, see https://specif.de/v0.11.7/schema.
The consistency checker will be updated accordingly in the coming weeks.

**Comment by odungern** [comment]
The consistency checker does not yet support multi-language enumerated values.

**Comment by oalt** [comment]
Supported in schema for 1.0
