### ISSUE TITLE
What type shall have the revision?

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#17]
Currently the revision is of type 'integer'. Thus, only sequential numbering is possible, but no branching. Also, document-databases have a more elaborated designation of revision.

Proposal: Change to 'string' and require that any newer revision is sorted in lexical order after any older.

@oalt : What do you think?

**Comment by odungern** [comment]
The problem of pure lexical ordering is that 11 < 2. The SpecIF:OrdinalMark is defined as follows ... and could be used as a revision scheme:

A string to determine the ordering of elements. Rules:

- For ordering, only alphanumeric characters are permissible. A letter case has no effect; for example, 'F' is equivalent to 'f'.
- The ordering at character level is alphanumeric, i.e. '1' < '7' < 'D' < 'X'.
- Single character substrings < two-character substrings < substrings with more characters, thus '9' < '12' < '114'.
- The ordinal mark may be separated by non-alphanumeric characters. All separators are equivalent; e.g. '-' is equivalent to ';' or '/'.
- Each alphanumeric substring is used for ordering on its hierarchical level; the leftmost substring is most significant for the overall ordering.
- For example '1' < '1.2' < '1.Y' < '1.1a' < '1-1b' < '1-1C' < '2'.

A regular expression for extracting the substrings of an ordinal mark is /([0-9a-z]+)[^0-9a-z]{0,1}/gi.

**Comment by odungern** [comment]
My proposal is:
```
"revision": {
    "description": "A revision tag with one or multiple alphanumeric character blocks separated by a single non-alphanumeric character. Sequential as well as branching revision sequences are possible.",
    "type": "string",
    "pattern": "^(?:[0-9a-zA-Z]+[.:,;\\-/])*[0-9a-zA-Z]+$"
}
```

**Comment by odungern** [comment]
Have a look at [SpecIF schema v0.10.8](https://specif.de/v0.10.8/schema).

**Comment by oalt** [comment]
Hello @odungern !
When you want to support branching and merging, you have not just to extend the Revision, but add a possibility to link to maximum 2 predecessor revisions:

### Example: Revision graph with branching and merging
main/1
main/2
main/3 -- myBranch/1 // Here a branch occurs
main/4`           `myBranch/2
main/5`           `|
main/6   - +  // Here a merge occurs
main/7


* main/6 is a merge of myBranch/2 and main/5. So main/6 has 2 predecessors: myBranch/2 and main/5.
* main/7 has just one predecessor: main/6. 
* main/1 has no predecessor (initial revision).

When SpecIF gets the possibility to define a current revision (still possible) and the possibility to define an array of predecessors (at least 2), I think then a complete branch/merge scenario can be supported.

**Comment by odungern** [comment]
... hmm, I am not expert in configuration management and so I am just wondering why predecessors are necessary. They haven't crossed my ways with CVS and SVN ... but I haven't fully embraced and understood GIT, yet (just using it happily under the hood ;-). 
On the other side, with predecessors we do not have the problem of finding an implicit sorting as discussed further up; any revision label would do. A simple and explicit way to document the branching and merging has certainly its advantages.
So, we would say:

```
"predecessors": {
      "type": "array",
      "minItems": 0,
      "maxItems": 2,
      "items": {
              "$ref": "#/definitions/revision"
      }
}
```
We need the predecessors with every element ... ? I'll think a little more.

**Comment by odungern** [comment]
Have a look at [SpecIF schema v0.10.8](https://specif.de/v0.10.8/schema).

**Comment by odungern** [comment]
.. is 'predecessor' a good name?  Have checked with RDF/RDFS and Dublin Core, but haven't found a term for previous revisions.

**Comment by odungern** [comment]
Looking again I found [dcterms:replaces](http://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/replaces/).

**Comment by odungern** [comment]
New property name for the predecessors in the revision history is 'replaces'. 
Have a look at [SpecIF schema v0.10.8](https://specif.de/v0.10.8/schema)

**Comment by odungern** [comment]
And have a look at [SpecIF schema v0.11.8](https://specif.de/v0.11.8/schema)

**Comment by odungern** [comment]
.. here, there is no need to add a constraint check; there is no need that the predecessor is present in the current SpecIF data-set.
