### ISSUE TITLE
Allow Statements to have a Statement as Subject or Object

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#19]
In trying mapping some data to SpecIF, I have the problem, that sometimes it would be very helpful, if you could add a Statement, that comes or goes from or to another statement. I provided just one example here:
![StamentToStaementExample](https://user-images.githubusercontent.com/10502268/56287119-d6f67c80-611b-11e9-8d38-5142898da006.png)
This diagram expresses, that the two resources and the writes-Statement are shown on the diagram. Currently this is not possible to express. You just can split the Statement between the two resources in two parts and add a "Dummy"-resource in the middle as Object for the shows statement. I think this is not a good solution to solve the problem.
No change at the schema definition is necessary. It is just a semantic change/extension, that a subject- or object-key in a statement can also reference to statements and not just to resources. 
Any other suggestions?

**Comment by odungern** [comment]
You are right, it is interesting where certain statements have been defined, especially in case of contradiction. You want to know which diagrams to look at and modify to resolve it. It is possible to restrict the possibility to certain statements such as SpecIF:shows by adding the permissible statementClasses to the subjectClasses or objectClasses of the respective statementClass.
You are also right, that the schema supports this already, but the constraint check would not accept it.
I agree and will make the modification of the constraint check as soon as I can. There is quite some work to be applied by now ..

**Comment by odungern** [comment]
- schemata [v0.10.8](https://specif.de/v0.10.8/schema) and [v0.11.8](https://specif.de/v0.11.8/schema) allow to specify statementClasses as subjectClasses or objectClasses without change. However the descriptions have been updated to reflect this possibility.
- The constraint checks need to be updaed, still.

**Comment by odungern** [comment]
The constraint checker for v0.10.8 and 0.11.8 have also been updated to reflect this change.
