### ISSUE TITLE
Stereotype property for which resource classes?

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#20]
Makes it sense to apply the property 'PC-Stereotype' to each SpecIF resource class or is this restricted to a specific subset? Which practical experience is available using the stereotype property?

**Comment by odungern** [comment]
So far, I have used a property with title 'SpecIF:Stereotype' as follows:
- In BPMN there are multiple types of events, such as 'startEvent', 'intermediateEvent' ... and about 15 others.
- All BPMN events would get a common resourceClass of with title = 'FMC:Event'.
- It gets a propertyClass with title = 'SpecIF:Stereotype'
- Then, a particular BPMN 'startEvent' would be an instance of the resourceClass with title 'FMC:Event' and the property with title 'SpecIF:Stereotype' gets a value 'BPMN:startEvent'.

Have a look at [BPMN-Example](https://specif.de/apps/view.html#import=%22../examples/BfdH_bestellen.bpmn%22)

Does this help in your situation?

**Comment by odungern** [comment]
.. so with respect to your question: There are several resourceClasses, where Stereotypes make sense, e.g. FMC:Actor, FMC:State, FMC:Event, IREB:Requirement and SpecIF:Feature. I haven't thought about the others, yet. 
In case of resourceClass with title SpecIF:Diagram I have used a property SpecIF:Notation to distinguish different types, for example.
So I do not see the need of a stereotype for all resources ...

**Comment by odungern** [comment]
The main criterion on whether a certain type/subtype becomes a resourceClass or just a stereotype of a more general resourceClass is:
- if you need a specific set of properties, consider to define a specialized resourceClass.
- if you need to specifically target an instance of a certain resourceClass with a statementClass (via subjectClasses and objectClasses), consider to define a specialized resourceClass. 
- For example: 'satisfies' is often defined as a statementClass, whose subjectClasses contain just 'FMC:Actor' and whose objectClasses contain just 'IREB:Requirement'. It is not possible to define similar constraints depending on property values such as "SpecIF:Stereotype":"BPMN:startEvent".

**Comment by odungern** [comment]
@oalt : if you see the need for additional discussion or a change of the schema, please reopen this issue.
