### ISSUE TITLE
Add System enumeration value to discipline

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#21]
I think it makes sense to have an additional value "System" in the Enumeration for the DT-Discipline to assign a requirement to a mechatronic System or a mechatronic control chain.

@odungern: What do you mean? Should we add such a value?

Definition reference: classDefinitions/102_EnumDatatypes.specif

**Comment by odungern** [comment]
The idea of 'discipline' is to denote the engineering discipline taking care of development. If you propose 'system', you mean the 'system engineering' discipline? In that case we can add 'system'.

**Comment by odungern** [comment]
I added the value as proposed: https://github.com/GfSE/SysML-SpecIF-Bridge/blob/master/classDefinitions/SysML-Template-v0.10.6.specif 

Actually, I think we should use vocabulary terms for all enumerated property values, such as 'SpecIF:priorityHigh' for priorities: https://specif.de/apps/view.html#import=%22../examples/Vocabulary.specifz%22
