### ISSUE TITLE
Icon can be a link/URL

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#23]
So far, an icon is a (short) string (e.g. allowing to specify UTF-8 characters), but @oalt proposes to allow a link to a graphical icon.

**Comment by odungern** [comment]
... what about a dataURL, such as:
- data:[&lt;mediatype&gt;][;base64],&lt;data&gt;

So, if the value attributed to icon is a dataURL, then it is decoded and shown. If it is not a dataURL, then it is taken as a string like in the past. It can still be a UTF-8 character, for example.

@oalt : What do you think?

**Comment by oalt** [comment]
Hello @odungern !
Your proposal is ok for me. 

By thinking about the icons: Would it be helpful to have the possibility to specify an icon not just in the type definitions, but also in the instances (Resources and Statements)? So it would be possible to specify specific icons for a concrete data element.
@odungern What do you think?

**Comment by odungern** [comment]
If we allow a dataURL, we could also allow an absolute or relative URL, which in case of HTML can be used in the same places as a dataURL.

But I suggest not to allow XHTML constructs such as &lt;img src="URL" /&gt;. 

Further Questions: 
- this means the referenced image must be supplied in the correct format and size, no formatting info can be added.
- should we add a RegEx to the schema, or leave it as a string type like it is currently?

**Comment by odungern** [comment]
An icon can be string, URL or dataURL, there will be no regex. Description updated with schema v1.0.0.
