### ISSUE TITLE
Node requires 'changedAt'

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#30]
For v1.0, 'changedAt' has been added to the required properties of a node (a nodes' item). Of course it will be set, when a node is created or modified. 
But in fact. also the parent is changed, if a node is added or moved So also set the changedAt of the parent? I propose not to do so, also because at root level, there is no parent. This feel a little strange, when moving a node with PUT and specifying parent resp. predecessor. Then the moved node gets a new change date, but not the affected parent nodes.
Have an opinion, @oalt, @oeichmann and @S-Ruesch ?

**Comment by oalt** [comment]
Supported in schema for 1.0 release
