### ISSUE TITLE
Remove restrictions from data types in base definitions

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#34]
Why are some numerical data type values in the Base Definitions restricted to a specific range?
* DT-Integer
* DT-Real
* DT-Decimal2
I would not restrict these data types ind the Base Definitions, because I think in practice we will have bigger numerical values to store.

**Comment by odungern** [comment]
Yes, you are right and I am not happy with it either. The question is whether we require a minimal and maximal limit. So far, the schema does not require 'minInclusive' and 'maxInclusive', whereas the consistency checker does require them.
Proposal: We remove the requirement for 'minInclusive' and 'maxInclusive' from the consistency checker and we remove it from the base-definitions, as well.

**Comment by odungern** [comment]
No objections, so this is agreed. Will close it as soon as the constraint-check is modified accordingly.

**Comment by odungern** [comment]
done.
