### ISSUE TITLE
New SpecIF logo for release 1.0?!

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#35]
I have made a new logo design for SpecIF based on the colors @odungern  had used in his logo design. The idea behind my design is
- The integrating aspect of SpecIF, symbolized by the central green hexagon
- The integrated systems/tools/formats around
- Use a font, that "expresses" the technical character of a file format
![grafik](https://user-images.githubusercontent.com/10502268/76029402-ab979e80-5f34-11ea-851b-2abfaf318c68.png)
@oeichmann @S-Ruesch @odungern What do you think about it? I am not a graphic designer. Perhaps anyone has a better idea... 

The used fonts are:
* _Rockwell Nova_ for 'SpecIF'
* _Rockwell Nova Light_ for 'Specification Integration Facility'

**Comment by odungern** [comment]
The above is much more relevant than the current clubs/clover. With respect to the logo I like a lot the incoming and outgoing path-ways to all directions. The SpecIF solution is sleak ... and so we should perhaps chose a sleak and less technical type face than Courier, in any case sans-serif. But this is a matter of taste.  

For comparison the current logo:
![specif-logo-100](https://user-images.githubusercontent.com/8947971/109989046-6903d000-7d08-11eb-8bdc-805e2b69cd50.png)

**Comment by oalt** [comment]
Here is another proposal with a sans-serif font. The used fonts are _SegoeUI Semibold_ for 'SpecIF' and _SegoeUI_ for 'Specification Integration Facility'
![grafik](https://user-images.githubusercontent.com/10502268/110200156-cf9a0280-7e5c-11eb-8eb7-691aebbb0bee.png)

**Comment by oalt** [comment]
New logo discussed and provided in the repository https://github.com/GfSE/SpecIF/tree/master/logo
