### ISSUE TITLE
Include $schema property in each SpecIF file

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#36]
Hello @odungern !

In my IDE there is an example of a JSON configuration file where at the beginning a property "$schema" with a schema reference is included.

Example:
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:60827",
      "sslPort": 44393
    }
  }, ...
```
What do you think - should we include such a property in each SpecIF file as well?

**Comment by odungern** [comment]
Indeed, that's only logical. Our schema states it's schema, as well.

Here, we have an example, where the schema has an extension *.json. In other cases, there is no extension. This is a detail, but perhaps the situation to reconsider this question.

**Comment by odungern** [comment]
Related issues:
- suppress specifVersion; no need if $schema is provided.
- should the specif data-set have 'id' or '$id'?
- host the schema as well on schemastore.org?  Looks as an interesting way to proliferate the idea, especially since some well-known editors draw from there.  However I have not seen yet how to submit a schema to be included.

**Comment by odungern** [comment]
Thanks, oalt for bringing up the topic. It is the 'dot on the i' (as we say in German) for v1.0!

**Comment by odungern** [comment]
I propose:
```json
    "$schema": {
      "type": "string",
      "format": "uri",
      "pattern": "^https?:\\/\\/(specif\\.de\\/v1\\.0\\/schema|.+\\/specif-1\\.0)\\.json$",
      "description": "An absolute URL pointing to this SpecIF schema."
    },
```
The first option points firmly at our own server, the second would allow to reference a schema hosted on schemastore.org.

**Comment by odungern** [comment]
With respect to extension .json or not. On schemastore.org:
- 87 entries have an extension .json
- 80 entries follow the example of json-schema,org and have no extension.

Following my guts, I would do like json-schema.org, but my experience does not like implicit knowledge in such cases, and so my proposal one step up does carry an extension ,,,

Your opinion @oalt @oeichmann @S-Ruesch ?

**Comment by odungern** [comment]
We could submit our schema here: [SchemaStore at GitHub](https://github.com/SchemaStore/schemastore)

**Comment by odungern** [comment]
... implemented according to proposal made above.
