### ISSUE TITLE
Remove  "minItems": 1 from dataTypes in schema

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#37]
In the dataTypes section in the schema is a restriction included to have at least 1 item in the array.

I think there are some use cases where no data types are included - if a SpecIF file uses just standardized data types and other metatypes.

So I suggest to remove this constraint from the schema.

**Comment by odungern** [comment]
.. agreed, it was a leftover from earlier times. We now can have valid SpecIF data without dataTypes ... and dataTypes can be omitted altogether.
There are other cases where it is a difference, whether there is _no_ list element or an _empty_ list element (for example in case of subjectClasses and objectClasses as part of statementClasses) ... but not here.
So I have removed the property.

(I wonder whether we should have: "uniqueItems": "true" .. but that's another story).
