### ISSUE TITLE
Allow multiple values

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#39]
We have discussed the requirement of multiple values per property. In fact, we already have all the ingredients: 'multiple' flag for enumerated values and value lists for multi-language strings. 
- Currently we say for a single value:
"value": "single-value" 
- and in case of a multivalued enumeration:
"value": "value-id-1,value-id-2".
- For a multilanguage string we use:
"value": [{"text":"content","language":"en"},{"text":"Inhalt","language":"de"}]
- So we could take just a list with strings for multiple values of any type: 
"value": ["value-1","value-2","value-3"].

However I propose to limit the variations of the "value" attribute and make it a list in all cases with one or more values.
- An enumeration would look like:
"value": ["value-id-1","value-id-2"] 
which is anyways better than before!
- A multi-valued property of any kind would be
"value": ["value-1","value-2","value-3"]
- and the multi-language string will not change.
- A single-valued property, however, would look like:
"value": ["single-value"] 

What do you think: @oalt @oeichmann @S-Ruesch ?

**Comment by oalt** [comment]
Hello @odungern !
I agree with your proposal but we have to change the multi-language value as well! It must be a array of arrays of text/language objects:

"value": [ [{"text":"content","language":"en"},{"text":"Inhalt","language":"de"}] , [ ... ] ]

Each value content is then an array containing either strings or multi-language values (array).

**Comment by odungern** [comment]
Of course, you are right, @oalt ! Will implement it as soon as possible.

**Comment by odungern** [comment]
Werde die Version auf 1.1 setzen, da es sich um einen 'breaking change' handelt.

**Comment by odungern** [comment]
implemented, see [SpecIF schema v1.1](https://specif.de/v1.1/schema.json).

**Comment by odungern** [comment]
We are just loosing the possibility to transform to ReqIF without loss.
Up to now we could create a ReqIF data-set by choosing a language and by factoring out inherited class info, for example, but I do not have an idea how to bring a list of >1 property values to ReqIF.
What do you think, @oalt @oeichmann @S-Ruesch

**Comment by odungern** [comment]
@oalt : Could you please formulate/explain your application challenge requiring multiple values? Perhaps we can find another solution.

**Comment by odungern** [comment]
To meet your challenge, @oalt : Can we add multiple property instances of the same propertyClass to a resource? Would need to specify a property identifier (which is optional in the schema) in this case to distinguish the values.
Need to check whether ReqIF allows multiple attributes of the same attribute-type; there is a better chance, however, than adding a value list to a single property instance.

**Comment by oalt** [comment]
@odungern : I thought about it again. Why do we not try to keep the compatibility to SpecIF schema 1.0? A value in 1.0 can be a simple string or an array of language: value pair. Why not just allow additionally to have an array of strings if the property class multiple is set to true or an array of langugae values for multi-language values.

So a value could be:
1. a siple string (property class value multiple is set to false)
2. an array of language values for the translations (property class value multiple is set to false)
3. an array of strings (property class value multiple is set to true)
4. an array of arrays to keep multiple language value (property class value multiple is set to true)

The tranlation to ReqIF could be realized by using comma seperated lists out of the multiple values.

A JSON parser is able to be configured to diffentiate between these 4 possible value representations.

What do you think? I belive by using such an implementation we can keep the compatibility to SpecIF 1.0.

**Comment by odungern** [comment]
Definitively this is possible for the cases you have listed. Howerver, in addition we have the enumerated values. Now, these are one or more comma-separated value-ids. If we introduce arrays to represent multiple values, I would like to do the same with a multivalued enumeration. This however this breaks with the current schema 1.0.
Of course one could also write the schema to accomodate for both cases. However, it becomes increasingly difficult to write code to properly treat all variants. The more variants are allowed by a schema, the less useful it becomes. (Like a firewall that opens more and more ports.) Even more so, because a schema cannot check the constraints. The dependency between the 'multiple' property and certain variants must be checked by the constraint checker. It is already quite complex ... and I am pretty sure nobody else did really scrutinize it yet - just today I stumbled by chance over a pretty bold weakness and have removed it. Making it complex reduces the 'beauty'. Also, the editor becomes more and more complex. 

You feel probably, I am not very happy about the multi-valued properties. Especially, since we are losing the lossless transformation to ReqIF. Did you think about adding multiple instances of a property with the same class? This should be similar in effect, but simpler to handle. One editor module per property ... and if a property appears several times, several fields open. I would have to look in the ReqIF xsd to see whether this passes or not.

Could you send a sample data set of your application, so that I can think a little more concretely?

**Comment by odungern** [comment]
Having discussed with @oalt , we will open the possibility for the future. Use-Case is a list of tags, for example. Rather than encoding multiple tag values in a comma-separated-string, we can now use an array of values; the attribute 'multiple' must be set to true.

Summarizing:
- if 'multiple' is undefined or false, a property-value is a string or a list of objects with text and language, as before.
- if 'multiple' is set to 'true', a property-value is a list with items as discussed above. 
- if 'multiple' is set to 'true' and the propertyClass is 'xs:enumerated', the property-value is now a list of value-ids. Up until v1.0 it has been a string with comma-separated value-ids.

Implemented, see [SpecIF schema v1.1](https://specif.de/v1.1/schema.json).

**Comment by odungern** [comment]
Reconsidering the issue today, I would like to propose a simpler solution:
- Starting v1.1, all properties have a value list, called 'values', to avoid different cases. 
- If 'multiple' is missing or false, the value list has 0..1 elements.
- If 'multiple' is true, the value list may have 0..n elements.
- In both cases it is recommended to omit the whole property, if there is no element in the value list.

An element is of different nature depending on the dataType as defined in the propertyClass:
- xs:string: element is a string *or* a list of objects with text and language
- xs:enumeration: element is an id of one of the values as defined in the dataType
- otherwise: element is a string (yes, numbers and booleans are also represented as strings)

**Comment by odungern** [comment]
With schema v1.1, properties have a value list for all dataTypes. These lists may have more than one items if the propertyClass or dataType has an attribute "multiple": true.
This solution, where even single values are provided in a list, has been chosen to avoid structure variants.
