### ISSUE TITLE
Publish schemata on https://www.schemastore.org/json/

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#42]
... starting with SpecIF v1.0

**Comment by odungern** [comment]
@oalt @oeichmann: Was haltet Ihr von schemastore.org?  Oder habt Ihr einen besseren Ort?

**Comment by oalt** [comment]
Koennen wir gerne machen. Da muesste man die Schema-Referenz in den SpecIF-Dateien daran anpassen. Das coole ist, wenn unter der URL im JSON wirklich das Schema erreicht wird, bekommt man in Visual Studio z.B. direkte Editierunterstuetzung beim manuellen bearbeiten und Intellisense :-)

**Comment by odungern** [comment]
.. genau. Den anderen Ort halte ich bei, so dass bestehende Dateien weiter funktionieren, doch als "offizielle" Stelle halte ich schemastore.org für gut geeignet. Übernehme das ... habe schon einmal geschaut, wie das geht ... ist nicht besonders schwer per Github. Nicht so gut gefällt mir allerdings, dass sie die Version in den Namen integrieren ... ist aber letztlich egal.

**Comment by odungern** [comment]
... done. Have a look at [schemastore.org](https://www.schemastore.org/json/). [SpecIF](https://json.schemastore.org/specif-1.0.json) is at the vey end - the next time I will put it in the correct alpha-numeric seqence.
