### ISSUE TITLE
Open questions about the schema

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#55]
When writing the documentation of the SpecIF-metamodel some questions came in my mind:

* What means the *type* attribute for the *Email* element?
* What means the *type* attribute for the *Rights* element?
* When the data type XHTML is no longer used, how is it expressed, that a string contains XHTML formatted text?

**Comment by odungern** [comment]
- type attribute in the email element: Idea was to specify "text/plain" or "text/html" as used by some e-mail applications. However this is not any more relevant, we have passed the 1990's. So the type attribute is dropped and then the e-mail can become a simple string with format "email".
- type in the rights element was misleading and has been dropped with schema v1.1, as well. Thanks for pointing it out.
- Now a property's value, if it is of dataType "xs:string", can have an attribute with enumerated values "plain" and "xhtml". I had considered to use official mime-types "text/plain" and "application/xhtml+xml", but those are defined for use with documents and not for text snippets.

Hopefully you agree with the proposals made ...
