### ISSUE TITLE
spellcheck of exported pdf

### ISSUE THREAD

**Issue by winf3** [GfSE/SpecIF#62]
I opened draft export Specif V1.1 in Word, ran the spellchecker and marked necessary changes which I found (see attached word file).
[SpecIF_Specification_draft_170821.docx](https://github.com/GfSE/SpecIF/files/7133885/SpecIF_Specification_draft_170821.docx)
 Have fun implementing !

**Comment by odungern** [comment]
Thanks a lot for your effort, Winfried!  We'll take care of it!

**Comment by odungern** [comment]
We have decided to use american-english spelling, so "analyze", "behavior" and "modeling" shall be used throughout ... but consistenty, which was not the case due to different authors collaborating.

**Comment by oalt** [comment]
Completely corrected over the entire specification and class definitions
