### ISSUE TITLE
Provide SpecIF templates

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#7]
@oalt :
Thanks for your effort to prepare the "semantics" folder. It is a good idea to provide some semantic guidelines: As you do, I believe that an agreed upon vocabulary makes the difference. And then, why not provide ready-to-use SpecIF-templates.

I would like to propose, however, to combine all x01_... files into a single one that is schema-compliant. Anyways, the resourceClasses need the dataTypes ...

In addition we could provide different templates for different purposes. For example we could provide a very simple template with just a resourceClass "requirement" having 4 propertyClasses in addition to the "full-fledged" template you have added. And perhaps somebody else has a different focus and supplies something different from the FMC fundamental model element types we both find useful for model integration. For example I recall a TdSE-2017 conference session by Markus Brandstätter proposing an "Artefaktmodell zur Verbesserung der Prozessmodellierung".

Finally, I propose to create a new file extension for templates, e.g. 'specift' and 'speciftz'. When importing, a new project id could be generated automatically (by convention) to assure that multiple projects based on the same template carry different identifiers.

What do you think?

**Comment by oalt** [comment]
Hello @odungern !
I have used different files for each class resp. data type definition to have a fine-granular overview as long as the definition process goes on and the discussion about the different classes. When a release of the semantics is done it makes sense to create a file containing the complete semantic definition in one.

**Comment by odungern** [comment]
@oalt :
Have a look: https://github.com/GfSE/SpecIF-Examples-and-Test-cases/tree/master/templates.
We could add some more and less elaborated templates for different target groups over time.
