### ISSUE TITLE
No automotive specific properties in IREB:Requirement

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#9]
I think the properties "PC-SupplierStatus", "PC-SupplierComment", "PC-OemStatus", "PC-OemComment" in the property class IREB:Requirement are to specific for a general definition of requirements. So I would suggest to remove them for the moment.
## Idea
As I thought about that, I had the idea if it makes sense to introduce an inheritance mechanism to SpecIF for the classes. This would provide the ability to define a general IREB:Requirement and a more special "Automotive Requirement" by just adding the newly needed properties ("PC-SupplierStatus", "PC-SupplierComment", "PC-OemStatus", "PC-OemComment") and inherit the rest from the base class. In the resource class we then have a new value e.g. `extends: "RC-Requirement"`.

**Comment by odungern** [comment]
... yes, also Markus Brandstätter thinks that inheritance is an important feature. We should think about it ... it is not difficult ... and you have already proposed a solution.
With respect to the HIS properties: I think this is not a beautiful, however proven method to communicate on single issues. At the same time not everybody needs it, probably it is only a minority. Anyways I propose to supply  multiple templates with different flavors and complexities ... and there could be an automotive requirements document template.

**Comment by odungern** [comment]
... so I agree with your proposal and have started by providing a very simple requirements-management template using the vocabulary terms as far as already defined: https://github.com/GfSE/SpecIF-Examples-and-Test-cases/tree/master/templates.

**Comment by oalt** [comment]
Hi @odungern !
I have updated the class definitions and removed the automotive-specific properties from the base-types. Additionally I added new resource classes e.g. VDA:Rrequirement. This classes extend the base types and provide the automotive-process-specific extension properties ("HIS-process").
